import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "../../../globals.css";
import "../../../globals.css";
import Header from "./_components/header";
import Sidebar from "./_components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen w-full flex-col bg-muted/40`}
    >
      <Sidebar />
      <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
        <Header />
        <main className="py-4 px-6">{children}</main>
      </div>
    </div>
  );
}
